# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_weights <- function(idx) {
    .Call(`_SingCellaR_compute_weights`, idx)
}

getDetectedGenesPerCell <- function(X, k) {
    .Call(`_SingCellaR_getDetectedGenesPerCell`, X, k)
}

getExpressingCellsPerGene <- function(X, k) {
    .Call(`_SingCellaR_getExpressingCellsPerGene`, X, k)
}

makeBinaryMatrix <- function(X, k) {
    .Call(`_SingCellaR_makeBinaryMatrix`, X, k)
}

makeBinaryMatrix_for_float <- function(X) {
    .Call(`_SingCellaR_makeBinaryMatrix_for_float`, X)
}

count_expressing_cells <- function(X, Y) {
    .Call(`_SingCellaR_count_expressing_cells`, X, Y)
}

count_divided_by_libsize <- function(X) {
    .Call(`_SingCellaR_count_divided_by_libsize`, X)
}

annoy_euclidean_nns <- function(index_name, mat, n_neighbors, search_k, grain_size = 1L, verbose = FALSE) {
    .Call(`_SingCellaR_annoy_euclidean_nns`, index_name, mat, n_neighbors, search_k, grain_size, verbose)
}

annoy_cosine_nns <- function(index_name, mat, n_neighbors, search_k, grain_size = 1L, verbose = FALSE) {
    .Call(`_SingCellaR_annoy_cosine_nns`, index_name, mat, n_neighbors, search_k, grain_size, verbose)
}

